<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="2" skipped="2">
  <reporter-output>
    <line>
      <![CDATA[hii am method1]]>
    </line>
    <line>
      <![CDATA[TC pass]]>
    </line>
    <line>
      <![CDATA[pass tc name isMymethod1]]>
    </line>
    <line>
      <![CDATA[ss taken]]>
    </line>
    <line>
      <![CDATA[fail tc name isMymethod2]]>
    </line>
    <line>
      <![CDATA[TC skipped]]>
    </line>
    <line>
      <![CDATA[skipped tc name isMymethod3]]>
    </line>
    <line>
      <![CDATA[hii am method1]]>
    </line>
    <line>
      <![CDATA[TC pass]]>
    </line>
    <line>
      <![CDATA[pass tc name isMymethod1]]>
    </line>
    <line>
      <![CDATA[ss taken]]>
    </line>
    <line>
      <![CDATA[fail tc name isMymethod2]]>
    </line>
    <line>
      <![CDATA[hii am method4]]>
    </line>
    <line>
      <![CDATA[TC pass]]>
    </line>
    <line>
      <![CDATA[pass tc name isMymethod4]]>
    </line>
    <line>
      <![CDATA[hii am method5]]>
    </line>
    <line>
      <![CDATA[TC pass]]>
    </line>
    <line>
      <![CDATA[pass tc name isMymethod5]]>
    </line>
    <line>
      <![CDATA[TC skipped]]>
    </line>
    <line>
      <![CDATA[skipped tc name isMymethod3]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-04T10:09:35 IST" name="Suite" finished-at="2022-07-04T10:09:36 IST" duration-ms="567">
    <groups>
    </groups>
    <test started-at="2022-07-04T10:09:35 IST" name="Test" finished-at="2022-07-04T10:09:36 IST" duration-ms="567">
      <class name="LisnerTest.MyTestNg2">
        <test-method signature="Mymethod1()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6]" started-at="2022-07-04T10:09:36 IST" name="Mymethod1" finished-at="2022-07-04T10:09:36 IST" duration-ms="12" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hii am method1]]>
            </line>
            <line>
              <![CDATA[TC pass]]>
            </line>
            <line>
              <![CDATA[pass tc name isMymethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod1 -->
        <test-method signature="Mymethod2()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6]" started-at="2022-07-04T10:09:36 IST" name="Mymethod2" finished-at="2022-07-04T10:09:36 IST" duration-ms="8" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at LisnerTest.MyTestNg2.Mymethod2(MyTestNg2.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[ss taken]]>
            </line>
            <line>
              <![CDATA[fail tc name isMymethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod2 -->
        <test-method signature="Mymethod4()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6]" started-at="2022-07-04T10:09:36 IST" name="Mymethod4" finished-at="2022-07-04T10:09:36 IST" duration-ms="13" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hii am method4]]>
            </line>
            <line>
              <![CDATA[TC pass]]>
            </line>
            <line>
              <![CDATA[pass tc name isMymethod4]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod4 -->
        <test-method signature="Mymethod5()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6]" started-at="2022-07-04T10:09:36 IST" name="Mymethod5" finished-at="2022-07-04T10:09:36 IST" duration-ms="3" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hii am method5]]>
            </line>
            <line>
              <![CDATA[TC pass]]>
            </line>
            <line>
              <![CDATA[pass tc name isMymethod5]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod5 -->
        <test-method signature="Mymethod3()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6]" started-at="2022-07-04T10:09:36 IST" name="Mymethod3" finished-at="2022-07-04T10:09:36 IST" depends-on-methods="LisnerTest.MyTestNg2.Mymethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MyTestNg2.Mymethod3()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MyTestNg2.Mymethod3()[pri:0, instance:LisnerTest.MyTestNg2@27f981c6] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC skipped]]>
            </line>
            <line>
              <![CDATA[skipped tc name isMymethod3]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod3 -->
      </class> <!-- LisnerTest.MyTestNg2 -->
      <class name="LisnerTest.MyTestNg">
        <test-method signature="Mymethod1()[pri:0, instance:LisnerTest.MyTestNg@f0da945]" started-at="2022-07-04T10:09:36 IST" name="Mymethod1" finished-at="2022-07-04T10:09:36 IST" duration-ms="24" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[hii am method1]]>
            </line>
            <line>
              <![CDATA[TC pass]]>
            </line>
            <line>
              <![CDATA[pass tc name isMymethod1]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod1 -->
        <test-method signature="Mymethod2()[pri:0, instance:LisnerTest.MyTestNg@f0da945]" started-at="2022-07-04T10:09:36 IST" name="Mymethod2" finished-at="2022-07-04T10:09:36 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at LisnerTest.MyTestNg.Mymethod2(MyTestNg.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[ss taken]]>
            </line>
            <line>
              <![CDATA[fail tc name isMymethod2]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod2 -->
        <test-method signature="Mymethod3()[pri:0, instance:LisnerTest.MyTestNg@f0da945]" started-at="2022-07-04T10:09:36 IST" name="Mymethod3" finished-at="2022-07-04T10:09:36 IST" depends-on-methods="LisnerTest.MyTestNg.Mymethod2" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MyTestNg.Mymethod3()[pri:0, instance:LisnerTest.MyTestNg@f0da945] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MyTestNg.Mymethod3()[pri:0, instance:LisnerTest.MyTestNg@f0da945] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[TC skipped]]>
            </line>
            <line>
              <![CDATA[skipped tc name isMymethod3]]>
            </line>
          </reporter-output>
        </test-method> <!-- Mymethod3 -->
      </class> <!-- LisnerTest.MyTestNg -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
